version: "3.8"

services:
  second-thought-backend:
    volumes:
      # Mount your local code into the container
      - .:/app
    environment:
      - ENV=development
    command: >
      uvicorn main:app
      --host 0.0.0.0
      --port 8000
      --reload
