apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: second-thought-backend-env
  namespace: second-thought-backend
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: second-thought-backend-env
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: apps/second-thought-backend/second-thought-backend/env
