apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: second-thought-backend-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  tls:
    - hosts:
        - second-thought-backend.krishnarajthadesar.in
      secretName: second-thought-backend-tls
  rules:
    - host: second-thought-backend.krishnarajthadesar.in
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: second-thought-backend
                port:
                  number: 8000
